## 1. Data cleaning pipeline quality (missing/outliers/scaling, reproducibility)

In [24]:
import pandas as pd

df = pd.read_csv("../data/Customer_data.csv")
df.head()

,Age,Gender,Marital Status,Occupation,Educational Qualifications,Family size,Frequently used Medium,Frequently ordered Meal category,Perference,Restaurnat Rating,...,Order Value,Ease and convenient,Self Cooking,Health Concern,Late Delivery,Poor Hygiene,Bad past experience,More Offers and Discount,Maximum wait time,Influence of rating
0,20,Female,Single,Student,Post Graduate,4,Food delivery apps,Breakfast,Non Veg foods (Lunch / Dinner),1,...,1,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,30 minutes,Yes
1,24,Female,Single,Student,Graduate,3,Food delivery apps,Snacks,Non Veg foods (Lunch / Dinner),1,...,3,Strongly agree,Strongly agree,Strongly agree,Agree,Strongly agree,Strongly agree,Strongly agree,30 minutes,Yes
2,22,Male,Single,Student,Post Graduate,3,Food delivery apps,Lunch,Non Veg foods (Lunch / Dinner),3,...,1,Strongly agree,Disagree,Neutral,Neutral,Agree,Agree,Neutral,45 minutes,Yes
3,22,Female,Single,Student,Graduate,6,Food delivery apps,Snacks,Veg foods (Breakfast / Lunch / Dinner),2,...,1,Agree,Agree,Strongly agree,Neutral,Agree,Disagree,Strongly agree,30 minutes,Yes
4,22,Male,Single,Student,Post Graduate,4,Walk-in,Lunch,Non Veg foods (Lunch / Dinner),3,...,3,Agree,Agree,Strongly agree,Strongly agree,Agree,Strongly agree,Agree,30 minutes,Yes

In [25]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                499 non-null    int64
 1   Gender                             498 non-null    str
 2   Marital Status                     499 non-null    str
 3   Occupation                         498 non-null    str
 4   Educational Qualifications         499 non-null    str
 5   Family size                        499 non-null    int64
 6   Frequently used Medium             498 non-null    str
 7   Frequently ordered Meal category   498 non-null    str
 8   Perference                         498 non-null    str
 9   Restaurnat Rating                  499 non-null    int64
 10  Delivery Rating                    499 non-null    int64
 11  No. of orders placed               499 non-null    int64
 12  Delivery Time                      498 non-null    str
 13  Order Value                        499 non-null    int64
 14  Ease and convenient                498 non-null    str
 15  Self Cooking                       499 non-null    str
 16  Health Concern                     498 non-null    str
 17  Late Delivery                      499 non-null    str
 18  Poor Hygiene                       499 non-null    str
 19  Bad past experience                498 non-null    str
 20  More Offers and Discount           498 non-null    str
 21  Maximum wait time                  497 non-null    str
 22  Influence of rating                499 non-null    str
dtypes: int64(6), str(17)
memory usage: 89.8 KB

,Age,Family size,Restaurnat Rating,Delivery Rating,No. of orders placed,Order Value
count,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000
mean,25.779559,3.350701,2.991984,2.959920,138.933868,1.969940
std,4.329722,1.510091,1.399920,1.413644,67.735678,0.826942
min,18.000000,1.000000,1.000000,1.000000,23.000000,1.000000
25%,23.000000,2.000000,2.000000,2.000000,80.500000,1.000000
50%,25.000000,3.000000,3.000000,3.000000,139.000000,2.000000
75%,29.000000,5.000000,4.000000,4.000000,199.500000,3.000000
max,35.000000,6.000000,5.000000,5.000000,257.000000,3.000000

In [26]:
df.isnull().sum()

Age                                  0
Gender                               1
Marital Status                       0
Occupation                           1
Educational Qualifications           0
Family size                          0
Frequently used Medium               1
Frequently ordered Meal category     1
Perference                           1
Restaurnat Rating                    0
Delivery Rating                      0
No. of orders placed                 0
Delivery Time                        1
Order Value                          0
Ease and convenient                  1
Self Cooking                         0
Health Concern                       1
Late Delivery                        0
Poor Hygiene                         0
Bad past experience                  1
More Offers and Discount             1
Maximum wait time                    2
Influence of rating                  0
dtype: int64

In [27]:
df.isnull().sum()

Age                                  0
Gender                               1
Marital Status                       0
Occupation                           1
Educational Qualifications           0
Family size                          0
Frequently used Medium               1
Frequently ordered Meal category     1
Perference                           1
Restaurnat Rating                    0
Delivery Rating                      0
No. of orders placed                 0
Delivery Time                        1
Order Value                          0
Ease and convenient                  1
Self Cooking                         0
Health Concern                       1
Late Delivery                        0
Poor Hygiene                         0
Bad past experience                  1
More Offers and Discount             1
Maximum wait time                    2
Influence of rating                  0
dtype: int64

In [28]:
df = df.dropna()

In [29]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [30]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})

In [31]:
df = df.drop_duplicates()

In [32]:
for col in df.columns:
    print(col, df[col].unique())

age [20 24 22 27 23 21 28 25 32 30 31 26 18 19 33 29 34 35]
gender [0 1]
marital_status <StringArray>
['Single', 'Married', 'Prefer not to say']
Length: 3, dtype: str
occupation <StringArray>
['Student', 'Employee', 'Self Employeed', 'House wife']
Length: 4, dtype: str
educational_qualifications <StringArray>
['Post Graduate', 'Graduate', 'Ph.D', 'Uneducated', 'School']
Length: 5, dtype: str
family_size [4 3 6 2 5 1]
frequently_used_medium <StringArray>
['Food delivery apps', 'Walk-in', 'Direct call', 'Web browser']
Length: 4, dtype: str
frequently_ordered_meal_category <StringArray>
['Breakfast', 'Snacks', 'Lunch', 'Dinner']
Length: 4, dtype: str
perference <StringArray>
[        'Non Veg foods (Lunch / Dinner)',
 'Veg foods (Breakfast / Lunch / Dinner)',
                  'Bakery items (snacks)',
                                 'Sweets']
Length: 4, dtype: str
restaurnat_rating [1 3 2 5 4]
delivery_rating [1 5 4 2 3]
no._of_orders_placed [150  32 193  60 234  55  77 172 224 165 225  27 103 233  54 210  30 163
 167  75  49  81  26  71 115  68 143 151 135  43 190 146 252 137 201  42
 221 149  94  89 114 158 102 195 184 147 255 182 118  79 173  82  76 107
 207 213 164 247 187 198 112 236 256 199 219  52 226 168 244 208 200  90
 231  86 142 129  80 109  64 133 228  33 101  48 188  24 127 216 138 116
 203 212 125 202 166 235 126  28  58 159 194 122 110 175 242 128 237 169
  98  56 250  61 140  78 248 197 104 134  62  85 179 105  72 214 254  88
  34 218  66  93  29  51  67 111  36  23  57  63 243  87 205  91 124 220
 239  65 132 189 145  46  96 141  53 144  74 154 153 160 257 206 177 222
 148 217 251 186 253 229  47  45 152 209  99  41 240 246 139 100 157 120
 162 232 130  35  38 156  44 181  83  84 238 192 113 155 117 185 211 191
 136 227 121 170  95 196 249  97]
delivery_time <StringArray>
[           '45',            '61',            '19',            '44',
            '24',            '39',            '18',            '56',
            '20',            '17',            '52',            '42',
            '46',            '27',            '51',            '40',
            '43',            '72',            '30',            '13',
            '32',            '63',            '22',            '31',
            '29',            '23',            '55',            '48',
            '60',            '35',            '62',            '53',
            '14',            '16',            '38',            '26',
            '73',            '47',            '41',            '21',
            '36',            '50',            '57',            '68',
            '49',            '15',            '12',            '54',
            '59',            '33',            '66',            '34',
            '28',            '58',            '11',            '64',
            '25',            '10',            '37',            '74',
            '65',            '71',            '67',            '70',
            '69',             '9', 'Delivery Time']
Length: 67, dtype: str
order_value [1 3 2]
ease_and_convenient <StringArray>
['Neutral', 'Strongly agree', 'Agree', 'Strongly disagree', 'Disagree']
Length: 5, dtype: str
self_cooking <StringArray>
['Neutral', 'Strongly agree', 'Disagree', 'Agree', 'Strongly disagree']
Length: 5, dtype: str
health_concern <StringArray>
['Neutral', 'Strongly agree', 'Agree', 'Strongly disagree', 'Disagree']
Length: 5, dtype: str
late_delivery <StringArray>
['Neutral', 'Agree', 'Strongly agree', 'Disagree', 'Strongly disagree']
Length: 5, dtype: str
poor_hygiene <StringArray>
['Neutral', 'Strongly agree', 'Agree', 'Disagree', 'Strongly disagree']
Length: 5, dtype: str
bad_past_experience <StringArray>
['Neutral', 'Strongly agree', 'Agree', 'Disagree', 'Strongly disagree']
Length: 5, dtype: str
more_offers_and_discount <StringArray>
['Neutral', 'Strongly agree', 'Agree', 'Disagree', 'Strongly disagree']
Length: 5, dtype: str
maximum_wait_time <StringArray>
['30 minutes', '45 minutes', '60 minutes', 'More than 60 minutes',
 '15 minutes']
Length: 5, dtype: str
influence_of_rating <StringArray>
['Yes', 'Maybe', 'No']
Length: 3, dtype: str

In [33]:
df = df.rename(columns={
    'no_of_orders_placed': 'demand',
    'restaurnat_rating': 'restaurant_rating'
})

In [34]:
# Remove wrong value
df = df[df['delivery_time'] != 'Delivery Time']

# Convert to numeric
df['delivery_time'] = df['delivery_time'].astype(int)

In [35]:
mapping = {
    'Strongly disagree': 1,
    'Disagree': 2,
    'Neutral': 3,
    'Agree': 4,
    'Strongly agree': 5
}

ordinal_cols = [
    'ease_and_convenient',
    'self_cooking',
    'health_concern',
    'late_delivery',
    'poor_hygiene',
    'bad_past_experience',
    'more_offers_and_discount'
]

for col in ordinal_cols:
    df[col] = df[col].map(mapping)

In [36]:
df = pd.get_dummies(df, drop_first=True)

In [37]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 486 entries, 0 to 498
Data columns (total 39 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   age                                                486 non-null    int64
 1   gender                                             486 non-null    int64
 2   family_size                                        486 non-null    int64
 3   restaurant_rating                                  486 non-null    int64
 4   delivery_rating                                    486 non-null    int64
 5   no._of_orders_placed                               486 non-null    int64
 6   delivery_time                                      486 non-null    int64
 7   order_value                                        486 non-null    int64
 8   ease_and_convenient                                486 non-null    int64
 9   self_cooking                                       486 non-null    int64
 10  health_concern                                     486 non-null    int64
 11  late_delivery                                      486 non-null    int64
 12  poor_hygiene                                       486 non-null    int64
 13  bad_past_experience                                486 non-null    int64
 14  more_offers_and_discount                           486 non-null    int64
 15  marital_status_Prefer not to say                   486 non-null    bool
 16  marital_status_Single                              486 non-null    bool
 17  occupation_House wife                              486 non-null    bool
 18  occupation_Self Employeed                          486 non-null    bool
 19  occupation_Student                                 486 non-null    bool
 20  educational_qualifications_Ph.D                    486 non-null    bool
 21  educational_qualifications_Post Graduate           486 non-null    bool
 22  educational_qualifications_School                  486 non-null    bool
 23  educational_qualifications_Uneducated              486 non-null    bool
 24  frequently_used_medium_Food delivery apps          486 non-null    bool
 25  frequently_used_medium_Walk-in                     486 non-null    bool
 26  frequently_used_medium_Web browser                 486 non-null    bool
 27  frequently_ordered_meal_category_Dinner            486 non-null    bool
 28  frequently_ordered_meal_category_Lunch             486 non-null    bool
 29  frequently_ordered_meal_category_Snacks            486 non-null    bool
 30  perference_Non Veg foods (Lunch / Dinner)          486 non-null    bool
 31  perference_Sweets                                  486 non-null    bool
 32  perference_Veg foods (Breakfast / Lunch / Dinner)  486 non-null    bool
 33  maximum_wait_time_30 minutes                       486 non-null    bool
 34  maximum_wait_time_45 minutes                       486 non-null    bool
 35  maximum_wait_time_60 minutes                       486 non-null    bool
 36  maximum_wait_time_More than 60 minutes             486 non-null    bool
 37  influence_of_rating_No                             486 non-null    bool
 38  influence_of_rating_Yes                            486 non-null    bool
dtypes: bool(24), int64(15)
memory usage: 72.1 KB

,age,gender,family_size,restaurant_rating,delivery_rating,no._of_orders_placed,delivery_time,order_value,ease_and_convenient,self_cooking,...,frequently_ordered_meal_category_Snacks,perference_Non Veg foods (Lunch / Dinner),perference_Sweets,perference_Veg foods (Breakfast / Lunch / Dinner),maximum_wait_time_30 minutes,maximum_wait_time_45 minutes,maximum_wait_time_60 minutes,maximum_wait_time_More than 60 minutes,influence_of_rating_No,influence_of_rating_Yes
0,20,0,4,1,1,150,45,1,3,3,...,False,True,False,False,True,False,False,False,False,True
1,24,0,3,1,1,32,61,3,5,5,...,True,True,False,False,True,False,False,False,False,True
2,22,1,3,3,5,193,19,1,5,2,...,False,True,False,False,False,True,False,False,False,True
3,22,0,6,2,4,60,44,1,4,4,...,True,False,False,True,True,False,False,False,False,True
4,22,1,4,3,1,234,24,3,4,4,...,False,True,False,False,True,False,False,False,False,True

In [38]:
cols_to_drop = [
    'ease_and_convenient',
    'self_cooking',
    'health_concern',
    'late_delivery',
    'poor_hygiene',
    'bad_past_experience',
    'more_offers_and_discount'
]

df = df.drop(columns=cols_to_drop)

In [39]:
df = df.rename(columns={
    'no._of_orders_placed': 'demand'
})

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 486 entries, 0 to 498
Data columns (total 32 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   age                                                486 non-null    int64
 1   gender                                             486 non-null    int64
 2   family_size                                        486 non-null    int64
 3   restaurant_rating                                  486 non-null    int64
 4   delivery_rating                                    486 non-null    int64
 5   demand                                             486 non-null    int64
 6   delivery_time                                      486 non-null    int64
 7   order_value                                        486 non-null    int64
 8   marital_status_Prefer not to say                   486 non-null    bool
 9   marital_status_Single                              486 non-null    bool
 10  occupation_House wife                              486 non-null    bool
 11  occupation_Self Employeed                          486 non-null    bool
 12  occupation_Student                                 486 non-null    bool
 13  educational_qualifications_Ph.D                    486 non-null    bool
 14  educational_qualifications_Post Graduate           486 non-null    bool
 15  educational_qualifications_School                  486 non-null    bool
 16  educational_qualifications_Uneducated              486 non-null    bool
 17  frequently_used_medium_Food delivery apps          486 non-null    bool
 18  frequently_used_medium_Walk-in                     486 non-null    bool
 19  frequently_used_medium_Web browser                 486 non-null    bool
 20  frequently_ordered_meal_category_Dinner            486 non-null    bool
 21  frequently_ordered_meal_category_Lunch             486 non-null    bool
 22  frequently_ordered_meal_category_Snacks            486 non-null    bool
 23  perference_Non Veg foods (Lunch / Dinner)          486 non-null    bool
 24  perference_Sweets                                  486 non-null    bool
 25  perference_Veg foods (Breakfast / Lunch / Dinner)  486 non-null    bool
 26  maximum_wait_time_30 minutes                       486 non-null    bool
 27  maximum_wait_time_45 minutes                       486 non-null    bool
 28  maximum_wait_time_60 minutes                       486 non-null    bool
 29  maximum_wait_time_More than 60 minutes             486 non-null    bool
 30  influence_of_rating_No                             486 non-null    bool
 31  influence_of_rating_Yes                            486 non-null    bool
dtypes: bool(24), int64(8)
memory usage: 45.6 KB

In [41]:
df = df.reset_index(drop=True)

In [42]:
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 32 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   age                                                486 non-null    int64
 1   gender                                             486 non-null    int64
 2   family_size                                        486 non-null    int64
 3   restaurant_rating                                  486 non-null    int64
 4   delivery_rating                                    486 non-null    int64
 5   demand                                             486 non-null    int64
 6   delivery_time                                      486 non-null    int64
 7   order_value                                        486 non-null    int64
 8   marital_status_Prefer not to say                   486 non-null    bool
 9   marital_status_Single                              486 non-null    bool
 10  occupation_House wife                              486 non-null    bool
 11  occupation_Self Employeed                          486 non-null    bool
 12  occupation_Student                                 486 non-null    bool
 13  educational_qualifications_Ph.D                    486 non-null    bool
 14  educational_qualifications_Post Graduate           486 non-null    bool
 15  educational_qualifications_School                  486 non-null    bool
 16  educational_qualifications_Uneducated              486 non-null    bool
 17  frequently_used_medium_Food delivery apps          486 non-null    bool
 18  frequently_used_medium_Walk-in                     486 non-null    bool
 19  frequently_used_medium_Web browser                 486 non-null    bool
 20  frequently_ordered_meal_category_Dinner            486 non-null    bool
 21  frequently_ordered_meal_category_Lunch             486 non-null    bool
 22  frequently_ordered_meal_category_Snacks            486 non-null    bool
 23  perference_Non Veg foods (Lunch / Dinner)          486 non-null    bool
 24  perference_Sweets                                  486 non-null    bool
 25  perference_Veg foods (Breakfast / Lunch / Dinner)  486 non-null    bool
 26  maximum_wait_time_30 minutes                       486 non-null    bool
 27  maximum_wait_time_45 minutes                       486 non-null    bool
 28  maximum_wait_time_60 minutes                       486 non-null    bool
 29  maximum_wait_time_More than 60 minutes             486 non-null    bool
 30  influence_of_rating_No                             486 non-null    bool
 31  influence_of_rating_Yes                            486 non-null    bool
dtypes: bool(24), int64(8)
memory usage: 41.9 KB

In [43]:
df.to_csv("../data/cleaned_food_delivery_data.csv", index=False)